[env:genericSTM32H750VB]
platform = ststm32
board = genericSTM32H750VB

; 1. 全局宣告使用我的配置
board_build.stm32cube.custom_config_header = yes

; 2. 告诉全局环境使用 softfp（为了兼容性）
board_build.float_abi = softfp
board_build.fpu = fpv5-d16

; 3. 编译标志（softfp 是我妥协了）
build_flags = 
    -mthumb
    -mcpu=cortex-m7
    -mfloat-abi=softfp
    -mfpu=fpv5-d16
    -D STM32H750xx
    -D USE_HAL_DRIVER
    -I include
    -I Drivers/STM32H7xx_HAL_Driver/Inc
    -I Drivers/CMSIS/Device/ST/STM32H7xx/Include
    -I Drivers/CMSIS/RTOS2/Include
    -I Drivers/CMSIS/Include
    -I Middlewares/Third_Party/FreeRTOS/Source/include
    -I Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
    -I Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F

; 4. 指定源文件编译路径
build_src_filter = 
    +<*> 
    +<../Drivers/STM32H7xx_HAL_Driver/Src/>
    +<../Middlewares/Third_Party/FreeRTOS/Source/>
    +<../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/>
    +<../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/>
    +<../Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c>

